### ISSUE TITLE
PDF mit CI erstellen

### ISSUE THREAD

**Issue by elogy** [fsi-tue/anfibrief#18]
Momentan muss man die PDFs mittels des Makefiles erstellen. Das ist auf Linux/MacOS gar kein Problem, auf Windows praktisch unmöglich. Um für die Windows-User der Zukunft das Leben einfacher zu machen, kam die Idee auf, mittels Continous Integration die PDF-Files automatisch zu erstellen.
Roman hat da in seiner BA was ähnliches gebastelt, bei Motivation und Zeit wäre das mal töfte ;)

**Comment by primeos** [comment]
Hatte ganz vergessen, dass es ja noch ein Issue dazu gab - ist seit https://github.com/fsi-tue/anfibrief/commit/6457c9eb174b11531d6de1e8acb4826657ecc673 implementiert :) #YAY
