### ISSUE TITLE
Neue Studiengänge

### ISSUE THREAD

**Issue by elogy** [fsi-tue/anfibrief#25]
Durch Umstellung im Lehramts-System und den neuen Machine Learning-Master brauchen wir neue Briefe und entsprechende Config-Flags für:

- Bachelor of Education (ehem. Lehramt)
- Master of Education
- Machine Learning

**Comment by Tammie47** [comment]
Da ML ja ein englisch sprachiger Studiengang ist, wäre es vielleicht auch nicht verkehrt, einen englischen Anfibrief(zunächst nur mit ML) zu machen. (Über das Anfi-Heft will ich erst gar nicht nachdenken^^')

**Comment by elogy** [comment]
Stimmt... urgh.
Da müsste man mal genauer in der Struktur wühlen. Rein theoretisch müsse man für die einzelnen Abschnitte englische Texte schreiben können, eine englische brief_main.tex anlegen, in der dann die englischen .tex-Files einbinden und dann dem englischen Brief sagen, dass er die englischen Files verwenden soll. Irgendwie so.
