### ISSUE TITLE
Possible mistake in Stundenplan

### ISSUE THREAD

**Issue by not-a-feature** [fsi-tue/anfibrief#45]
The "Informatik 1" lecture is not uniform among the timetables. 

In "Kognitionswissenschaft" the lectures takes places on Tuesday 14-16 and Thursday 14-16 but in every other study programme there is no lecture on Thursday.

### affected files: 
- stundenplaene/stpl_bioinfo-bsc.tex
- stundenplaene/stpl_informatik-bsc.tex
- stundenplaene/stpl_informatik-lehramt.tex
- stundenplaene/stpl_medieninfo-bsc.tex
stundenplaene/stpl_medinfo-bsc.tex

**Comment by luoe** [comment]
Should be fixed in ff74c78d614c1b340ed8e27c87d7d8ca21c6ddc8.

See also https://teri.fsi.uni-tuebingen.de/anfibrief/brief_kogwiss-bsc.pdf

**Comment by luoe** [comment]
Info I is only on Tuesdays in the timetable that Prof. Menth sent to me, but the videos will probably be uploaded to YouTube before the regular start of the lecture.
