### ISSUE TITLE
Kogni Student Union as part of the FSI

### ISSUE THREAD

**Issue by not-a-feature** [fsi-tue/anfibrief#46]
The introduction says that the FSI also consist of the "Kognitionswissenschaft" student union. 
But on the same page it refers to two different unions different web-links.

`Wir, die Fachschaft Informatik, sind einigeStudenten aus den Fächern Informatik, Bioinformatik, Medieninformatik, Kognitionswissenschaft undMedizininformatik, die sich für die Interessen der Studenten einsetzen.`
and 
`Auf unserer Homepagehttps://www.fsi.uni-tuebingen.de(oderhttps://www.fs-kogni.uni-tuebingen.de/für Kognis) findestdu bereits jetzt viele hilfreiche Informationen rund ums Studium.`

**Comment by luoe** [comment]
Thanks!

This should be fixed in 2b4e471087a248b2b2c4738e4bab879105a802ca
